name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build docker images
      run: docker-compose build
    - name: Setup database
      run: docker-compose run setup
    - name: Run tests
      run: docker-compose run test
