name: Test
on:
  pull_request:
  workflow_dispatch :
  push: { branches: master }

jobs:
  RunTest:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build docker images
      run: docker-compose build
    - name: Setup database
      run: docker-compose run setup
    - name: Run tests
      run: docker-compose run test
